### PR TITLE
Fix versions of tools

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by timosachsenberg** [comment]
looks good

**Comment by Zethson** [comment]
```
Test #15 - Param multiqc_config from nextflow config not found in nextflow_schema.json
Test #15 - Param igenomes_base from nextflow config not found in nextflow_schema.json
Test #15 - Param igenomes_ignore from nextflow config not found in nextflow_schema.json
```

@jpfeuffer @drpatelh 
We don't need igenomes nor mutlqic as a proteomics pipeline.

We could either just add them anyways (which is meh) or relax the nf-core linting requirements @drpatelh ?
Unfortunately, nf-core linting is not really customizable (yet).
As a first fix I suggest that these parameters should lead to warnings and not failures in the linting.

If you agree I can open an issue @tools.

**Comment by jpfeuffer** [comment]
Yes, I agree that it would be better as a warning. Maybe we could even adapt linting based on a label in the pipeline.
If "genomics" -> error. Then we could think about some standardization rules for proteomics as well.

**Comment by jpfeuffer** [comment]
Actually, after fixing, I think the problem is not so much about linting but about the templates.
By default, I think the templates will add back those parameters. There should be an option for specific pipelines to not have certain parts, like "igenomes" and "multiqc" (although I am currently trying to abuse the multiqc email function with ptxqc).

**Comment by drpatelh** [comment]
You can just remove those particular parameters @Zethson @jpfeuffer. That's what I have done for the image analysis pipeline I have written and this will also get the [linting passing](https://github.com/nf-core/imcyto/pull/37). There is a [`TODO`](https://github.com/nf-core/tools/blob/f14c7a5692c96896c2ed1b730bc355093dca2247/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/main.nf#L306) in the pipeline template for a couple of the `multiqc` params, maybe we can add some for the `igenomes_*` ones too. Be great if you can create an issue :)

**Comment by Zethson** [comment]
@jpfeuffer yeah, the sync will add those back, since the template is based on a NGS QC example.
But since there usually are so many conflicts anyways it doesn't really matter in the grand scale of merge conflict fixing...

**Pull request merged**
