### PR TITLE
change sdrf version -> 0.0.10

### PR DESCRIPTION
**Pull request by ypriverol**
## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] If necessary, also make a PR on the [nf-core/proteomicslfq branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/proteomicslfq)

### CODE REVIEW

**Comment by jpfeuffer** [comment]
There seem to be problems. The PLFQ tool cannot parse "Sample 1". It expects pure consecutive integers starting from one.

**Comment by ypriverol** [comment]
The new version of Sdrf-pipelines is now ready.

**Comment by jpfeuffer** [comment]
Looks good. Is this ready to merge?

**Comment by ypriverol** [comment]
@jpfeuffer this is ready to be merged?

**Review by jpfeuffer — APPROVED** [review]

**Pull request merged**
