### PR TITLE
[FEATURE] Added json schema

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by Zethson** [comment]
@jpfeuffer was this generated with the current nfcore tools development version?

**Comment by jpfeuffer** [comment]
Yes, correct.

**Comment by jpfeuffer** [comment]
Still have to copy over the descriptions from the docs.

**Comment by jpfeuffer** [comment]
And potentially add some restrictions.

**Comment by jpfeuffer** [comment]
Guys I am going to merge to have this part in the upcoming sync.

**Pull request merged**
