### PR TITLE
Some fixes and add test data for phospho

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by Zethson** [comment]
Paths to the test files seem wrong though?

**Comment by Zethson** [comment]
@jpfeuffer haha I just saw the mail "requested review" and though it was this PR. Didn't notice that it was solely the test file PR :)

**Comment by jpfeuffer** [comment]
Ah, the nextflow wheel of death.. great..

**Comment by jpfeuffer** [comment]
Hallelujah!

**Pull request merged**
