### PR TITLE
Fix/msstats one condition

### LINKED ISSUE #6: running comet without posterior error probabilities crashed
./nextflow run nf-core/proteomicslfq --spectra "MZML/* 50000 *mzML" --database uniprot_yeast_reviewed_isoforms_ups1_crap.fasta_td.fasta --expdesign experimental_design_short.tsv --search_engine comet -profile singularity -r dev

### PR DESCRIPTION
**Pull request by jpfeuffer**
fixes #6

### CODE REVIEW

**Comment by jpfeuffer** [comment]
wait I will add a param to completely skip msstats

**Comment by Zethson** [comment]
If you're using print statements in the scripts to give the user feedback you should add 

`echo true`

in the process definition. Else, stdout won't be printed to the console.

**Comment by jpfeuffer** [comment]
Hmm true, but it will have a lot of other std output as well.

**Comment by Leon-Bichmann** [comment]
While testing for the phospho data I just realized there is a small bug in the decoy database generation step.

**Pull request merged**
