### PR TITLE
add a tools folder

### PR DESCRIPTION
**Pull request by jpfeuffer**
For collecting useful downstream scripts.

### CODE REVIEW

**Comment by Zethson** [comment]
Can't we add them as optional processes?
If not, what's the reason? Do they not work with every input?

**Comment by jpfeuffer** [comment]
Yes kind of. They are sometimes a bit dependent on the experimental design and what kind of analysis you want to do.
Also the thing that I did is an interactive visualization, so you would need to start up R studio with a GUI to look at the results.

**Comment by Zethson** [comment]
I see.
Guess this would be the first pipeline to ship 'external' scripts, which are not part of the pipeline itself.

**Comment by jpfeuffer** [comment]
I know and honestly I would probably make a new repository once a critical mass is reached. But for one "show-casing" script, it was not really worth it.

**Pull request merged**
