### PR TITLE
Update msstats_plfq.R

### PR DESCRIPTION
**Pull request by timosachsenberg**
# nf-core/proteomicslfq pull request

Many thanks for contributing to nf-core/proteomicslfq!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/proteomicslfq branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/proteomicslfq)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/proteomicslfq/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Now you can see the error.

**Comment by jpfeuffer** [comment]
This would be cool to have for a release as well.

**Comment by jpfeuffer** [comment]
Can you rebase or something?

**Comment by timosachsenberg** [comment]
k just a sec

**Comment by timosachsenberg** [comment]
hmm can't push on this PR

**Comment by jpfeuffer** [comment]
you can also make a new one

**Comment by jpfeuffer** [comment]
I think a new one is better.

**Pull request closed without merging**
