### PR TITLE
Manual merge of TEMPLATE 1.12

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by Zethson** [comment]
:tada: 

much better :)

**Comment by jpfeuffer** [comment]
Should I force-push the TEMPLATE branch now? So the sync uses the clean version next time? Or how does it work?

**Comment by Zethson** [comment]
I think that the TEMPLATE branch should get deleted, so that it gets recreated the next time a sync occurs.
But I may be wrong, so maybe a quick question in #tools?

**Comment by jpfeuffer** [comment]
I did delete it and recreated it with a manual `nf-core sync .`
Question would be, if I only push the delete or if I push the "clean" TEMPLATE branch.

**Comment by Zethson** [comment]
I tend more towards option 1, but don't rely on my answer :)

**Pull request merged**
